import { StyleSheet } from 'react-native';

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      alignItems: 'center',
      width: '100%',
      height: '200px',
    },
    text: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#fff',
    },
    image: {
      flex: 1,
      width: '100%',
      height: '200px',
      justifyContent: 'center',
      alignItems: 'center',
    },
    arrow: {
      position: 'absolute',
      left: 20,
      top: 20,
      width: 50,
      height: 50,
    },
    liveText: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: '30px',
      textAlign: 'center',
      fontFamily: 'Roboto',
      fontSize: 30,
      color: '#fff',
    },
    teamContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 60,
      justifyContent: 'center', // Adicionado para centralizar os elementos horizontalmente
    },
    teamImage: {
      width: 80,
      height: 80,
      marginHorizontal: 10,
    },
    scoreText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#fff',
      marginHorizontal: 10,
    },
    cardContainer: {
      borderRadius: 8,
      elevation: 4,
      marginHorizontal: 16,
      marginVertical: 10,
      padding: 16,
      backgroundColor: 'transparent',
    },
    historyContainer: {
      position: 'absolute',
      top: '27%',
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 1,
      width: '100%',
      height: '100%',
    },
    history: {
      position: 'absolute',
      top: '0',
      width: '94%',
      height: 200,
      shadowColor: '#4D4D4D',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 4,
      borderRadius: 8,
    },
    shadow: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 20,
    },
    menuContainer: {
      position: 'absolute',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      backgroundColor: '#F5F5F5',
      top: '450px',
      width: '100%'
    },
    menuText: {
      fontSize: 18,
      fontWeight: 'bold',
    },
    teamIconsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    teamIcon: {
      width: 30,
      height: 30,
      marginHorizontal: 8,
    },
    playerItem: {
      fontSize: 20,
      fontWeight: 'bold',
      padding: 8,
      borderWidth: 1,
      borderColor: '#D9D9D9',
      height: 60,
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      marginTop: 10,
      marginBottom: 10,
      backgroundColor: '#FFFFFF',
      shadowColor: '#9A9A9A',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      borderRadius: 10,
    },  
    playerList: {
      position: 'absolute',
      top: 520,
      width: '100%',
      padding: 5,
      color: '#767676',
      fontFamily: 'Inter',
      fontWeight: 500,
      overflow: 'scroll',
      backgroundColor: '#F5F5F5',
    },
    playerIcon: {
      width: 40,
      height: 40,
    },
    playerName: {
      marginLeft: 12,
      fontSize: 23,
    },
    goal: {
      position: 'absolute',
      zIndex: 10,
      width: '100vw',
      height: '35vh',
      top: '70vh',
    },
    betButton: {
      position: 'absolute',
      bottom: 20,
      right: 20,
      backgroundColor: '#FFC107',
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingVertical: 8,
      zIndex: 20,
    },
    betButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#fff',
    },
    modalContainer: {
      backgroundColor: '#FFF',
      borderRadius: 8,
      padding: 20,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    modalTitleSave: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 10,
      color: '#5cbc7c',
    },
    modalText: {
      fontSize: 16,
      marginBottom: 20,
    },
    qrCodeImage: {
      width: 200,
      height: 200,
      alignSelf: 'center',
      marginBottom: 20,
    },
    closeButton: {
      backgroundColor: '#EAEAEA',
      borderRadius: 8,
      padding: 10,
      alignItems: 'center',
    },
    closeButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#333',
    },
    apostarButton: {
      backgroundColor: '#5cbc7c',
      borderRadius: 8,
      padding: 10,
      alignItems: 'center',
      marginBottom: 10,
    },
    apostarButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#fff',
    },
    input: {
      backgroundColor: '#F5F5F5',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      color: '#000',
      marginBottom: 16,
    },
  });

  export default styles;
